### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-graphics-audio#115]
Hi @galibzon @thefranke! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by vincent6767** [comment]
Hi @galibzon @thefranke!, a friendly reminder to help review by next week as we want every SIG to have a roadmap according to the RFC attached above by February 6th, 2023.

**Comment by thefranke** [comment]
Hi, just as in the other thread:

https://github.com/orgs/o3de/projects/41/views/1

**Comment by vincent6767** [comment]
Hi! Responded in this thread: https://github.com/o3de/sig-graphics-audio/pull/96#issuecomment-1415050076

**Comment by vincent6767** [comment]
Friendly reminder @thefranke @galibzon 
Can you help also add a kind/roadmap label to your roadmap item in this project? https://github.com/orgs/o3de/projects/41/views/1

Once that's done, I'll close the ticket!

**Comment by galibzon** [comment]
> Friendly reminder @thefranke @galibzon Can you help also add a kind/roadmap label to your roadmap item in this project? https://github.com/orgs/o3de/projects/41/views/1
> 
> Once that's done, I'll close the ticket!

@vincent6767 , I don't understand what is needed here. I don't see an option to add a Label to https://github.com/orgs/o3de/projects/41/views/1

Can you show me an example?

**Comment by vincent6767** [comment]
https://github.com/o3de/sig-graphics-audio/pull/96
According to this PR, you need to add a few labels to your repo. @galibzon Let me know if you have any questions.

**Comment by vincent6767** [comment]
Talked with @thefranke He pointed out that the item is labeled as kind/roadmap. Thanks for the confirmation!
![image](https://user-images.githubusercontent.com/15702735/221637655-3cfa7f44-f6b4-412a-9cb8-0b16c8e11294.png)
