### ISSUE TITLE
Reviewer Nomination: jhmueller-huawei

### ISSUE THREAD

**Issue by jhmueller-huawei** [o3de/sig-graphics-audio#123]
### Nomination Guidelines
**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE

1. https://github.com/o3de/o3de/pull/10118
2. https://github.com/o3de/o3de/pull/10141
3. https://github.com/o3de/o3de-atom-sampleviewer/pull/472
4. https://github.com/o3de/o3de/pull/11700
5. https://github.com/o3de/o3de/pull/11701
6. https://github.com/o3de/o3de/pull/14644
7. https://github.com/o3de/o3de/pull/14719

100+ lines of code changed across all contributions submitted to O3DE

The first commit already manages that.

2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer

I hope to get the support of @moudgils and @thefranke.

Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: jhmueller-huawei, to become a Reviewer/Maintainer on behalf of sig-graphics-audio. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/jhmueller-huawei

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by thefranke** [comment]
I support this nomination. Joerg is working on some rather large code chunks in the RHI and has gathered extensive knowledge, so they will make a great reviewer.

**Comment by moudgils** [comment]
I support the nomination

**Comment by galibzon** [comment]
I support the nomination

**Comment by thefranke** [comment]
Can we close this ticket @moudgils ?

**Comment by moudgils** [comment]
Closing this issue with the assumption that jhmuller is added to reviewer list

**Comment by jhmueller-huawei** [comment]
Yes, I've been added in the meantime :)
