### ISSUE TITLE
[ISSUE][DOCS] Asset link is broken and additional information should be added when using other project than AutomatedTesting

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/sig-graphics-audio#133]
## Describe the issue

Project requirements state that "Any Project built which uses Atom as its rendering Agent. AutomatedTesting is good.", however when using the MeshBase.prefab (mentioned below) on a new project there have to be some additional adjustments made. sphere_5lods.fbx asset is available only in AutomatedTesting, so it has to be copied over and Mesh0, Mesh1, Mesh2, Mesh3, Mesh4 as well as Mirror Ball have to be manually updated with their respective meshes for the setup to be functional.

Additionally the "Aquire and invoke prefab MeshBase.prefab" link (https://github.com/o3de/sig-graphics-audio/blob/main/prefabs/MeshBase.prefab) is incorrect and should be https://github.com/o3de/sig-graphics-audio/blob/main/testing-guidance/workflow-tests/materials/prefabs/MeshBase.prefab.

## Impacted page(s)

https://github.com/o3de/sig-graphics-audio/blob/main/testing-guidance/workflow-tests/materials/editor_mesh_materials.md

**Comment by smurly** [comment]
updated the link and clarified the prefab is for use with AutomatedTesting

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
