### ISSUE TITLE
Reviewer Nomination: kh-huawei

### ISSUE THREAD

**Issue by jhmueller-huawei** [o3de/sig-graphics-audio#145]
### Nomination Guidelines
**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE

25 merged PRs: https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Akh-huawei+

100+ lines of code changed across all contributions submitted to O3DE

e.g.: https://github.com/o3de/o3de/pull/16269 (+220 −164)

2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer

I support and hope to also get support  from @VickyAtAZ.

Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***kh-huawei***, to become a ***Reviewer*** on behalf of ***sig-graphics-audio***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile *** https://github.com/kh-huawei ***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lgleim** [comment]
I also support this nomination

**Comment by VickyAtAZ** [comment]
I support this nomination

**Comment by thefranke** [comment]
@amzn-changml @galibzon This has gone through, can we get Karl the necessary rights?

**Comment by amzn-changml** [comment]
@jhmueller-huawei has been invited
