### ISSUE TITLE
Reviewer Nomination: msat-huawei

### ISSUE THREAD

**Issue by jhmueller-huawei** [o3de/sig-graphics-audio#146]
### Nomination Guidelines
**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE

9 merged PRs: https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Amsat-huawei+

100+ lines of code changed across all contributions submitted to O3DE

e.g.: https://github.com/o3de/o3de/pull/16343 (+144 −53)

2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer

I support and hope to also get support  from @VickyAtAZ.

Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***msat-huawei***, to become a ***Reviewer*** on behalf of ***sig-graphics-audio***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile *** https://github.com/msat-huawei ***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by moudgils** [comment]
Nomination approved. Tagging @amzn-changml to help with adding the nominee to https://github.com/orgs/o3de/teams/sig-graphics-audio-reviewers. Thanks

**Comment by amzn-changml** [comment]
Added to the team
