### ISSUE TITLE
Maintainer Nomination: jhmueller-huawei

### ISSUE THREAD

**Issue by jhmueller-huawei** [o3de/sig-graphics-audio#149]
### Nomination Guidelines
**Maintainer Nomination Requirements**
Has been a Reviewer for 2+ months

21 PRs reviewed in total since end of March (5 months): https://github.com/o3de/o3de/issues?q=reviewed-by%3Ajhmueller-huawei+

8+ reviewed Pull Requests in the previous 2 months

9 PRs reviewed in July and August so far: https://github.com/o3de/o3de/issues?q=reviewed-by%3Ajhmueller-huawei+

200+ lines of code changed across all reviewed Pull Request

E.g.: not merged (still waiting for second review):

https://github.com/o3de/o3de/pull/16341 (+484 −6)

Or merged:

https://github.com/o3de/o3de/pull/16342 (+66 −45)
https://github.com/o3de/o3de/pull/16343 (+144 −53)

2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer

I hope to get the support of @moudgils and @thefranke.

Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate myself: ***jhmueller-huawei***, to become a ***Maintainer*** on behalf of ***sig-graphics-audio***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/jhmueller-huawei

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by thefranke** [comment]
Joergs track record speaks for itself. I support this nomination.

**Comment by moudgils** [comment]
Nomination approved. Tagging @amzn-changml to help with adding the nominee to https://github.com/orgs/o3de/teams/sig-graphics-audio-reviewers as well as https://github.com/orgs/o3de/teams/sig-graphics-audio-maintainers. Thanks

**Comment by amzn-changml** [comment]
@jhmueller-huawei has been invited
