### ISSUE TITLE
Election of new co-chair for sig-graphics-audio

### ISSUE THREAD

**Issue by thefranke** [o3de/sig-graphics-audio#157]
Hello all, having too many hats on at the moment I would like to hand over my position as co-chair of sig-graphics-audio. This has [already been mentioned in the TSC meeting](https://github.com/o3de/tsc/blob/main/meetings/notes/tsc-meeting-20240116.md#agenda-item-from-thefranke).

You can see the election process here: https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md

**Comment by Naomi-Wash** [comment]
This election is complete: https://github.com/o3de/sig-graphics-audio/issues/158
