### ISSUE TITLE
SIG-graphics-audio 11/30 release notes

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-graphics-audio#21]
Please fill any info related to the below for the 11/30 release notes: Note this has a due date of Friday Nov 12th, 2021

 * Features
 * Bug fixes (GHI list if possible)
 * Deprecations
 * Known issues

**Comment by santorac** [comment]
Known issues:

MaterialType Default Values Not Initially Applied. When changing a default material property value, materials may continue using the prior default value.
https://github.com/o3de/o3de/issues/5213

MaterialType New Property Not Initially Applied. When adding new material properties, the Asset Processing may initially fail for material files, and the AP needs a re-scan or restart.
https://github.com/o3de/o3de/issues/5215

**Comment by Adi-Amazon** [comment]
Features / New Gem:
AtomTressFX hair gem was implemented, displaying cutting edge hair technology based on the TressFX 4.1 In this version we introduced and improved both rendering methods (PPLL and ShortCut) and implemented the advanced Marshcner lighting model.

**Comment by santorac** [comment]
- Material files are now backward compatible with material property renames, by defining version updates in the .materialtype file.
- Reduced build dependencies on .materialtype files so that modifying shader code will no longer cause all .material and .fbx files to reprocess.

**Comment by moudgils** [comment]
RHI work
- Add support for refresh rate and sync interval support
- Enable Azslc for Linux
- Add support for xcb connections for Linux/Vulkan
- Add Renderdoc support via command line
- Add Pix support via command line
- Move RHI settings into settings registry
- Added GPU Buffer/Image memory visualizer
- AtomStarter game related fixed for mobile
- Enabled PipelineLibrary support to enable PSO caching for DX12 and Vulkan
- CPUProfiler is promoted from RHI to O3de
- Added support for GPU descriptor heap compaction for DX12 in case the gpu visible descriptor heap fragments
- Add support for taskgraph to SRG compilation
- Optimize SRG compilation to allow partial SRG updates
- Enable parallel encoding for Vulkan
- Fix a bunch of Vulkan validation errors
- Fix null descriptor issues for devices without null descriptor extension.
- Multiple fixes done to managing and creation of Vk swapchain

**Comment by wintermute-motherbrain** [comment]
Release notes captured and latest release available.
