### ISSUE TITLE
Reviewer Nomination: tjmgd

### ISSUE THREAD

**Issue by tjmgd** [o3de/sig-graphics-audio#28]
----
name: SIG Reviewer/Maintainer Nomination Template
about: Nominate yourself or someone else to become a SIG reviewer or maintainer
title: 'SIG Reviewer/Maintainer Nomination'
labels: 'needs-triage,needs-sig'

---
### Nomination Guidelines
**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE
100+ lines of code changed across all contributions submitted to O3DE
2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
Has been a Reviewer for 2+ months
8+ reviewed Pull Requests in the previous 2 months
200+ lines of code changed across all reviewed Pull Request
2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***tjmgd***, to become a ***Reviewer*** on behalf of ***sig-graphic-audio***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/tjmgd***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by rgba16f** [comment]
I approve.

**Comment by wintermute-motherbrain** [comment]
Approved by sig-graphics on 2022-02-16

**Comment by amzn-changml** [comment]
Added to the sig-graphics-audio-reviewers team
