### ISSUE TITLE
Nominations for new chair

### ISSUE THREAD

**Issue by wintermute-motherbrain** [o3de/sig-graphics-audio#34]
**What:** Jon B (discord: JonB [Amazon] / github: wintermute-motherbrain) is stepping down as chair of sig-graphics-audio.
**When:** New nominations are being held as of 2022-04-07 and will continue until 2022-04-20 (the next sig-graphics-audio monthly)

Please reply to this ticket with a nomination.  If you wish to +1 (vote) for someone that has been nominated, please use the **_thumbs up_** emoji.

**Comment by wintermute-motherbrain** [comment]
Nomination: galibzon

**Comment by thefranke** [comment]
Nomination: @bindless-chicken (Thomas Poulet)

**Comment by superkitcath** [comment]
Based on the number of votes on 2022-04-20, at 10:20 PDT, @galibzon is replacing @wintermute-motherbrain as chair of sig-graphics-audio.
