### ISSUE TITLE
Reviewer/Maintainer Nomination: gadams3

### ISSUE THREAD

**Issue by gadams3** [o3de/sig-graphics-audio#45]
----
name: SIG Reviewer/Maintainer Nomination Template
about: Nominate yourself or someone else to become a SIG reviewer or maintainer
title: 'SIG Reviewer/Maintainer Nomination'
labels: 'needs-triage,needs-sig'

---
### Nomination Guidelines
**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE
100+ lines of code changed across all contributions submitted to O3DE
2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
Has been a Reviewer for 2+ months
8+ reviewed Pull Requests in the previous 2 months
200+ lines of code changed across all reviewed Pull Request
2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: @gadams3, to become a Reviewer+Maintainer on behalf of @o3de/sig-content @o3de/sig-graphics-audio. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/gadams3

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by amzn-phist** [comment]
I support this nomination.

**Comment by mbalfour-amzn** [comment]
I support this nomination.

**Comment by thefranke** [comment]
Needed to update the sig-graphics-audio reviewer list
