### ISSUE TITLE
Reviewer Nomination: Thomas Poulet @bindless-chicken

### ISSUE THREAD

**Issue by thefranke** [o3de/sig-graphics-audio#46]
### Nomination Guidelines

**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE
100+ lines of code changed across all contributions submitted to O3DE
2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
Has been a Reviewer for 2+ months
8+ reviewed Pull Requests in the previous 2 months
200+ lines of code changed across all reviewed Pull Request
2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

### Reviewer/Maintainer Nomination

I would like to nominate: ***@bindless-chicken***, to become a ***Reviewer*** on behalf of ***sig-graphics-audio***. The requirements will be met with the next accepted PR.

* Nominee's GitHub Profile ***https://github.com/bindless-chicken***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by rgba16f** [comment]
I support this nomination.

**Comment by thefranke** [comment]
Approved as reviewer.
