### ISSUE TITLE
Maintainer Nomination: HogJonny-AMZN

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/sig-graphics-audio#47]
I would like to nominate: ***HogJonny-AMZN***, to become a ***Maintainer*** on behalf of ***sig-graphics-audio***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/HogJonny-AMZN***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by gadams3** [comment]
I support this nomination

**Comment by amzn-phist** [comment]
I support this nomination

**Comment by Bindless-Chicken** [comment]
I support this nomination.

**Comment by thefranke** [comment]
Approved as maintainer, please close issue.
