### ISSUE TITLE
Reviewer Nomination: @santipaprika

### ISSUE THREAD

**Issue by thefranke** [o3de/sig-graphics-audio#65]
### Nomination Guidelines
**Reviewer Nomination Requirements**
6+ contributions successfully submitted to O3DE
100+ lines of code changed across all contributions submitted to O3DE
2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

### Reviewer/Maintainer Nomination

I would like to nominate: ***@santipaprika***, to become a ***Reviewer*** on behalf of ***sig-graphics-audio***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/santipaprika***

Santi's code submissions so far: [O3DE](https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Asantipaprika+is%3Aclosed), [o3de-sampleviewer](https://github.com/o3de/o3de-atom-sampleviewer/pulls?q=is%3Apr+author%3Asantipaprika+is%3Aclosed), with a total of 6 PRs. The eye shader alone is > 700 lines.

**Comment by tjmgd** [comment]
I second this

**Comment by Bindless-Chicken** [comment]
I support this nomination.
