### ISSUE TITLE
RFC: Material Pipeline Abstraction Design

### ISSUE THREAD

**Issue by santorac** [o3de/sig-graphics-audio#68]
The content of this RFC has been moved to a PR, to make use of change history since I needed to make some revisions to what was a rather large document, and to allow easier commenting for reviewers.

See https://github.com/o3de/sig-graphics-audio/pull/76

**Comment by santorac** [comment]
I made a prototype implementation of the proposed system here: https://github.com/aws-lumberyard-dev/o3de/tree/Atom/santorac/MaterialPipelinePrototype

Most things worked out as expected, but I learned some things along the way that warrant minor updates to the proposal. I'll post further comments with those details a bit later.

**Comment by santorac** [comment]
I moved the content of this RFC to [a wiki page](https://github.com/o3de/sig-graphics-audio/wiki/RFC:-Material-Pipeline-Abstraction-Design) and then made a bunch of updates based on my findings from the [prototype](https://github.com/aws-lumberyard-dev/o3de/tree/Atom/santorac/MaterialPipelinePrototype).
1. Instead of copying a bunch of template AZSL code into a generate .azsl file, we should #include the template code to take advantage of the Shader Asset Builder's dependency tracking.
2. Instead of updating making the .materialtype have separate shader lists for each pipeline, we can just add some pipeline tag information to each item in the current list. This will be simpler to implement and easy to maintain backward compatibility.
3. There are multiple ways we could make the runtime arrange the shaders into the proper pipeline, but I like the idea of putting pipeline filter information into the RHI DrawItem. It's simple, and keeps the door open for possibly reusing the same DrawItem in multiple pipelines.
4. We are probably going to need a material pipeline tag name instead of just using the render pipeline name, in order to allow a material pipeline to work with multiple render pipelines.

See the draft PR for the exact details https://github.com/o3de/o3de/pull/12111

**Comment by jeremyong-az** [comment]
Could we have the RFC submitted as a PR to the rfcs folder to let folks comment and ask questions? (I believe this is the standard RFC process)

**Comment by santorac** [comment]
> Could we have the RFC submitted as a PR to the rfcs folder to let folks comment and ask questions? (I believe this is the standard RFC process)

Done. The links above have been updated to point to https://github.com/o3de/sig-graphics-audio/pull/76

**Comment by galibzon** [comment]
Approved.

**Comment by santorac** [comment]
Here is the committed document: https://github.com/o3de/sig-graphics-audio/blob/main/rfcs/MaterialPipelineAbstraction.md
