### ISSUE TITLE
Maintainer Nomination: @adiblev

### ISSUE THREAD

**Issue by thefranke** [o3de/sig-graphics-audio#75]
### Nomination Guidelines
**Maintainer Nomination Requirements**
Has been a Reviewer for 2+ months
8+ reviewed Pull Requests in the previous 2 months
200+ lines of code changed across all reviewed Pull Request
2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

### Reviewer/Maintainer Nomination

I would like to nominate Adi Bar Lev, to **restore/transfer** his rights as a Maintainer and all his previous rights. I verify that they have fulfilled the prerequisites for this role. Adi's previous account was @Adi-Amazon, which he no longer has access to, therefore I would like to request to transfer the rights from @Adi-Amazon to @adiblev.

* Nominee's GitHub Profile ***https://github.com/adiblev***
* Nominee's inaccessible GitHub Profile ***https://github.com/Adi-Amazon***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lgleim** [comment]
I'm happy to support this nomination!

**Comment by galibzon** [comment]
@adiblev is already both a maintainer and a code reviewer. Since 9/15/2022.
