### ISSUE TITLE
Proposed RFC Feature: Variable Rate Shading

### ISSUE THREAD

**Issue by akioCL** [o3de/sig-graphics-audio#87]
### Summary:
Traditionally, the density of fragment shader invocations for a given triangle is constant across the framebuffer. Due to performance constraints, a graphics renderer can't always afford to deliver the same level of quality to every part of its output image. Variable-rate shading—or coarse pixel shading—is a mechanism that lets you allocate rendering performance/power at rates that vary across your rendered image.

In some cases, the shading rate can be reduced with little or no reduction in perceptible output quality; leading to a performance improvement that's essentially free of charge.

### What is the relevance of this feature?

One of the most common bottlenecks for graphic applications is the cost of shader invocations done during a frame. As resolutions continue to increase, this problem is exacerbated and any saving in this area becomes even more important. This is specially true for VR platforms, where resolutions double and framerate demands are high. Shading millions of pixels at high speed is crucial for maintaining a great experience and avoiding VR sickness.

Mobile platforms would also benefit tremendously from using VRS. Not only it would reduce the number of shader invocations, but also decrease the bandwidth usage. Bandwidth requires a significant amount of power, something that is limited on mobile platforms. Too much power usage means heat, which translates to throttling, which decrease even more the resources available. Bandwidth is the number one limiting factor on mobile, where power efficiency is critical.

VRS can deliver performance gains across multiple platforms with some (small) compromises. When used properly, the decrease in quality can be negligent. VRS can be tweaked by developers to find a good balance between performance and quality.
 
The GPU Web project did an [analysis](https://github.com/gpuweb/gpuweb/issues/450) about the frametime reduction using VRS on iOS running the Amazon Bistro scene. 

![image](https://user-images.githubusercontent.com/10719597/195648717-f6e55553-91e2-4976-8e10-09129c0bcd39.png)

Using variable rasterization rate for this scene causes a 31% reduction in frame time (which corresponds to a 45% increase in fps). Here are the images of variable rasterization rate on and off, so you can judge the quality:

With VRS:
![image](https://user-images.githubusercontent.com/10719597/195648837-67721e21-540b-4e76-b93d-06d3c1d26df6.png)

Without VRS:
![image](https://user-images.githubusercontent.com/10719597/195648880-13592f24-cb6b-4dce-9936-06361c0b9f46.png)

### Feature design description:

VRS is a platform dependent feature. Different graphic APIs implement it in a slightly different manner. The goal of the design is to present a common interface so developers can implement once, and run in multiple platforms without major differences.

The first step is to analyze how VRS is implemented in the supported graphic APIs:

**DX12**

DirectX 12 provides 3 different mechanisms to control the shading rate. Different mechanisms are available depending on the hardware feature tier.

**- Per draw:** you can specify a shading rate that will affect all touched fragments during the draw call.  To enable VRS you do it through the command list. This mode is available on all tiers.

**- Per screen-space image (image-based):**: On Tier 2 and higher, you can specify the pixel-shading rate with a screen-space image.
The screen-space image allows your application to create a "level-of-detail (LOD) mask" image indicating regions of varying quality, such as areas that will be covered by motion blur, depth-of-field blur, transparent objects, or HUD UI elements. The resolution of the image is in macroblocks; it's not in the resolution of the render target. The values in the rate map represent the enum density enum values themselves. The screen-space image for specifying the shader rate is set on the command list.

**- Per primitive:** : A per-primitive attribute adds the ability to specify a shading rate term as an attribute from a provoking vertex.
The per-primitive attribute is a settable semantic named SV_ShadingRate. SV_ShadingRate exists as part of HLSL Shader Model 6.4. This is available on Tier 2 and higher.

Because there are 3 different ways of specifying rasterization rates, D3D includes a system of “combiners” which combine these 3 signals into a final rasterization rate. These combiners are configurable.

**Vulkan**

Vulkan provides two different extensions to support VRS.
- [VK_KHR_fragment_shading_rate](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_fragment_shading_rate.html): This extension provides up to three methods to the application to change the fragment shading rate:

    - [Per draw](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#primsrast-fragment-shading-rate-pipeline): the shading rate is specified through the pipeline or dynamically through the command buffer.

    - [Per screen-space image](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#primsrast-fragment-shading-rate-attachment): Allows the specification of a rate per-region of the framebuffer, specified in a specialized image attachment. The attachment shading rate can be set by including [VkFragmentShadingRateAttachmentInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkFragmentShadingRateAttachmentInfoKHR) in a subpass to define a fragment shading rate attachment. 

    - [Per primitive](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#primsrast-fragment-shading-rate-primitive): Allows the specification of a rate per primitive, specified during shading. The per-primitive attribute is a settable semantic named SV_ShadingRate. SV_ShadingRate exists as part of HLSL Shader Model 6.4

    Additionally, these rates can all be specified and combined in order to adjust the overall detail in the image at each point. 

- [VK_EXT_fragment_density_map](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_fragment_density_map.html): This extension provides only one way to set the shading rate. 

    - **Per screen-space image**: An image can be bound as a fragment density map attachment to a render pass. This image contains normalized (x, y) float component fragment density values for regions of the framebuffer that will be used in rasterization for every subpass. An important point to mention about this extension is that the Subpass color and depth attachments can be created as subsampled (storing only the low-resolution tile data in system memory and recreating the upscaled data only at sampling time). This subsampled layout reduces memory bandwidth (critical on mobile) and allows for selective upscaling, resulting in better visual quality. Unfortunately render targets that are subsampled have restrictions at the moment of texture reading. This images have to be sampled using a sampler created with the flag VK_SAMPLER_CREATE_SUBSAMPLED_BIT_EXT or through the use of a combined image sampler with an immutable sampler. Taking advantage of subsampled render targets will require support from AZSLc.

    This is the only VRS extension that is present on the Oculus Quest 2.

**Metal**

Support is only present in iOS, not macOS. Metal uses a different approach than D3D or Vulkan. It only provides one way of specifying the shading rate, but is not through an image, command list method or shading variable. Instead it sub divides the screen in a grid and specify a horizontal and vertical rasterization rates for each cell. This subdivision is called a rasterization map and is used during a renderpass.

Another big difference is that you have to do a two-pass algorithm. In the first pass, you render your scene into a small texture using the rasterization map previously created. These textures are smaller because you allocate only the memory you need to hold the rendered pixels. Smaller textures means a decrease in bandwidth usage (critical one mobile). Then, for the second pass, you render your scene into the normal-sized framebuffer, and sample from the output texture of the first pass. The shading language includes a new opaque type, rasterization_rate_map_data, which exposes an API to let you convert between arbitrary points on the real destination and the input texture. This is needed in order to properly sample the intermediate reduced size textures.

```
fragment float4 transformMappedToScreenFragments(
        PassThroughVertexOutput in [[stage_in]],
        constant rasterization_rate_map_data &data [[buffer(0)]],
        texture2d<half> intermediateColorMap    [[ texture(0) ]])                                                 
{
    constexpr sampler s(coord::pixel, address::clamp_to_edge, filter::linear);
    rasterization_rate_map_decoder map(data);
    float2 physCoords = map.map_screen_to_physical_coordinates(in.position.xy);    
    return float4(intermediateColorMap.sample(s, physCoords));     
}
```
At the moment, SPIRV-Cross does not support these new MSL operations ([ticket](https://github.com/KhronosGroup/SPIRV-Cross/issues/1015)) so there's no way to emit the proper commands from HLSL to MSL.

### Technical design description:

Since there's some significant differences between on how the APIs implement VRS, the design will need to be flexible so developers can choose the approach that fit them better. We identify 4 different ways to specify the shading rate: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/akioCL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/akioCL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  | Per Draw | Per Primitive | Per Image | Per Grid
-- | -- | -- | -- | --
DX12 | Yes | Maybe | Maybe | Maybe
Vulkan | Maybe | Maybe | Maybe | Maybe
Metal | No | No | No | Maybe

</body>

</html>

DX12 and Vulkan don't technically support a "Per Grid" mode, but these modes could be emulated using the "Per Image" mode if available.

The first step is exposing which modes the platform supports at runtime. For this we add a new member to the RHI::DeviceFeatures struct.

```
enum class ShadingRateType : uint32_t
{
    PerDraw,
    PerPrimitive,
    PerImage,
    PerGrid,
    Count,
    Invalid = Count
};
static const uint32_t ShadingRateTypeCount = static_cast<uint32_t>(ShadingRateType ::Count);

enum class ShadingRateTypeFlags : uint32_t
{
    None = 0,
    PerDraw= AZ_BIT(static_cast<uint32_t>(ShadingRateType ::PerDraw)),
    PerPrimitive = AZ_BIT(static_cast<uint32_t>(ShadingRateType ::PerPrimitive)),
    PerImage = AZ_BIT(static_cast<uint32_t>(ShadingRateType ::PerImage )),
    PerGrid = AZ_BIT(static_cast<uint32_t>(ShadingRateType ::PerGrid )),
    All = PerDraw| PerPrimitive | PerImage | PerGrid 
};

AZ_DEFINE_ENUM_BITWISE_OPERATORS(AZ::RHI::ShadingRateTypeFlags )
```

```
struct DeviceFeatures
{
....
   ShadingRateTypeFlags m_ShadingRateTypeMask = ShadingRateTypeFlags::None;
...
}
```
**Per-Draw mode:**
For this mode we'll add the following command to the RHI::CommandList class

```
class CommandList
{
...
    using ShadingRateCombinators = AZStd::array<ShadingRateCombinerOp, 2>;
    virtual void SetFragmentShadingRate(ShadingRateType rate, const ShadingRateCombinators* combinators = nullptr);
...
}

enum class ShadingRate : uint32_t
{
    1x1 = 0,
    1x2,
    2x1,
    2x2,
    2x4,
    4x2,
    4x4,
    Count
} ;

enum class ShadingRateCombinerOp : uint32_t
{
    Passthrough = 0,
    Override,
    Min,
    Max
} ;
```

**Per-Image mode:**

![image](https://user-images.githubusercontent.com/10719597/196227412-b030079c-d543-457f-bb7e-a71615c59473.png)

The first step for using this mode is to create the image that will be use as the shading rate mask. For calculating the size of the image we need to add the Tile size to the DeviceFeatures struct

```
struct DeviceFeatures
{
....
   RHI::Size m_rateShadingTileSize;
...
}
```
For a render target of size {rtWidth, rtHeight}, using a given tile size named VRSTileSize, the screen-space image that will cover it is of these dimensions.

`{ ceil((float)rtWidth / VRSTileSize), ceil((float)rtHeight / VRSTileSize) }`

We need to add a new RHI::ImageBindFlags, because on Vulkan you need to specify that the image will be use as a shading rate attachment when being created.

```
AZ_ENUM_CLASS_WITH_UNDERLYING_TYPE(ImageBindFlags, uint32_t,
...
    (ShadingRate, AZ_BIT(7)),
...
```

Now that we have the texture created we need to generate the content with the shading rate values. Since the way to represent these values is different depending on the API and runtime support, we will need a way to map the "ShadingRate" enum to actual values that goes in the texture.

```
class Device
{
...
   virtual uint8_t ConvertShadingRate(ShadingRate rate) = 0;
...
}
```

To be able to use the image in a Scope of the Framegraph we need to add a new ScopeAttachmentUsage:

```
enum class ScopeAttachmentUsage : uint32_t
{
...
    //! An attachment used for specifying the framebuffer shading rates 
    ShadingRate,
...
};
```

If we want to take advantage of subsample rendertargets we need to do a couple of more things.
First, we need to create the rendertarget texture with a special flag. To do this we add a new attribute to the MultisampleState of the Image Descriptor:

```
struct MultisampleState
{
...
    bool m_subSampled = false;
...
}
```

Second, for reading the texture we need to use a sampler that was created with a specific flag. Because of this we would need a way to specify that a sampler will be used with a texture that is subsampled. One way of doing this is adding some metadata in the shader and using AZSLc to add that information in the reflection data of the shader.

```
[[subsampled]]
Sampler m_sampler
{
    MaxAnisotropy = 16;
    AddressU = Wrap;
    AddressV = Wrap;
    AddressW = Wrap;
};
```
**Per-Primitive mode:**

The per-primitive attribute is a settable semantic named SV_ShadingRate. SV_ShadingRate exists as part of [HLSL Shader Model 6.4](https://learn.microsoft.com/en-us/windows/desktop/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12). Currently, AZSLc only accepts SM 6.1 grammar and so does the DXC version used by O3DE. Enabling this mode will require an update of AZSLc and DXC to SM 6.4.

**Per-Grid mode:**

Since this is only useful for Metal, and at the moment SPIR-V Cross doesn't support the needed semantic, this section will be TBD.

### What are the advantages of the feature?
**Quality**
Upscaling the low-resolution data only during sampling improves the quality of [bilinear filtering](https://en.wikipedia.org/wiki/Bilinear_interpolation), as neighboring pixels in system memory now contain true neighbor data since the rendering has not been previously upscaled. Also, focusing the quality in the parts that are needed increase the general perception.

**Bandwidth**
As resolutions continue to increase, bandwidth savings are becoming more and more important. This is especially true in standalone form factors where power efficiency is critical. Foveation enhancements combat this by only writing out and reading in the required data to system memory. Storing the low-resolution tile data in memory reduces the write bandwidth during rendering and also reduces the read bandwidth when the texture is sampled. In XR content, we typically see write bandwidth savings of around 30% to 40%.

**Performance**
At its core VRS rendering is a performance enhancing feature that could substantially improves the framerate  In XR content we typically see 2-3x performance improvement. Depending on the level of quality this can grow to as high as 4x. This is enabling developers to achieve higher framerates and resolutions.

As eye tracking technology becomes more prevalent, further gains can be achieved by moving the focal point of the foveation to follow the [fovea](https://en.wikipedia.org/wiki/Fovea_centralis) where we have highest resolution, and shading less in the peripheral areas where we see less detail.

### What are the disadvantages of the feature?
Decrease of general Quality: Since using this feature requires fine tuning the level of shading quality, artifacts could appear, or maybe too low quality is used in areas that are very visible to users.

### How will this be implemented or integrated into the O3DE environment?
The plan is to implement VRS in parts. Since the current need is for the Quest 2 device, the initial implementation will focus on Vulkan, using the [VK_EXT_fragment_density_map](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_fragment_density_map.html) extension, since it's the only one supported on the device.

Developing on Android is slow, so to speed up the process for the initial development the extension [VK_KHR_fragment_shading_rate](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_fragment_shading_rate.html) will be used (available on PC). We will focus in the Per-Image mode, and use a decreased quality level on the edges of the screen.
![image](https://user-images.githubusercontent.com/10719597/196225178-a2a9d943-5306-4721-8e46-afae716abc9c.png)

Subsampled rendertargets and Combinators will not be supported at this point. 
At this moment we start working on the Atom Viewer Sample using the new provided functionalities of the RHI. Once the sample is running using the VK_KHR_fragment_shading_rate "Per-Image" mode on PC, we switch to implement the VK_EXT_fragment_density_map extension on Android.
After the sample runs on the Quest 2 using the VK_EXT_fragment_density_map extension, the next step will be to implement the "Per-draw" mode, since it should be pretty easy to add.
Once this is done, we will move to implement the same "Per-Image" and "Per-draw" mode in DirectX12 implementation of the RHI.
Finally Subsampled rendertargets and Combinators functionality is added.

### Are there any alternatives to this feature?
- The simple alternative is reducing the size of the render targets used and upscale before presenting to the screen. This would decrease the bandwidth and the number of shading invocations, but at a cost of quality through the whole screen. With this approach we cannot focus the quality in areas that are important (like the center in VR content).
- Another approach is using a Fixed Foveated Rendering (FFR) provided by the platform. Certain VR devices (e.g. Quest 2) provides fixed areas where the quality is automatically decrease. These areas cannot be change and they only work if the app is rendering directly to the swapchain images. Currently, the O3D3 pipelines do not render to the swapchain, but to intermediate textures and at the content is copy to the swapchain as the last command. This approach is only limited to certain VR devices.

### How will users learn this feature?
- A sample will be added to the "Atom Sample Viewer" to showcase how users can take advantage of this feature. The usage of the feature will be added to the existing pipelines. The sample will be documented so developers understand how to take advantage of this feature and how to add it to their pipelines.

### Are there any open questions?
- Metal has a different approach to the VRS implementation. Without SPIR-V Cross supporting sampling of the rasterization rate map we cannot do the implementation on Metal. Should we add an effort to try to support it on iOS? Maybe if Apple releases a VR device it's worth it to implement it for Metal.

**Comment by moudgils** [comment]
The RFC looks good overall. Just a few comments/questions
- For [[subsampled]] tag will we need Azslc support?
- Do we need to even consider "Per Draw" mode once we add "Per Image" mode?
- We should consider having a mode where we can write directly to the swapchain image and use platform provided FFR support. Although this may require setting up a separate pipeline maybe.
- For metal we should wait for the device to come out first and we may need to take a very different approach at that time. For now lets just focus on DX12/Vulkan as emulating grid support for dx12/vk sounds more complex and may be less performant.

**Comment by jeremyong-az** [comment]
> upgrade DXC to SM 6.4

We wouldn't be able to do this globally but will need a requirement to flag shaders as needing VRS support. Not all platforms support it at the moment so on some restricted platforms, we wouldn't want to attempt to build/ship PSOs that require VRS

**Comment by moudgils** [comment]
Since this RFC is accepted please open a PR and move this RFC to this folder - https://github.com/o3de/sig-graphics-audio/tree/main/rfcs where we will track all the new RFCs for book keeping purposes. Thanks.

**Comment by wangwei46810** [comment]
Hi，when I run the Modern Rending with Metal demo and put off VRR button, smaller size of rendering image exists on the left top of the screen. Do you know how to deal with it ? In a word, how to show full-screen resolution when I truned of VRR algorithm ? Thank you .
