### ISSUE TITLE
Add @invertednormal as a Maintainer

### ISSUE THREAD

**Issue by invertednormal** [o3de/sig-graphics-audio#9]
- Has been a Reviewer since June
- Reviewed 12 PRs in July,  21 PRs in August, so far 10 in September
- Changed far more than 200 lines of code (18 commits in July, 5 in August, thousands of lines of code total)

**Comment by wintermute-motherbrain** [comment]
Hi @invertednormal,

Can you please re-create a new issue using the "ContributorNominationTemplate"?  

Thank you
